Add Contribute command
thewilloftheshadow/jt99-janitor pull request #4
Opened 2024-03-24 23:29 UTC by ooTruffle

This tag tells users how they are able to add a new tag to Janator if they think something should be added

2024-03-25 00:15 UTC, thewilloftheshadow requested changes

2024-03-25 00:15 UTC, thewilloftheshadow commented on src/commands/index.ts
> +import contribute from "./tage/contribute"
Typo

2024-03-25 08:44 UTC, ooTruffle reviewed
i... i can english i swear

2024-03-25 16:16 UTC, thewilloftheshadow approved these changes

2024-05-10 14:01 UTC, ooTruffle commented
Also added the "app" change

2024-08-22 15:44 UTC, Associationgreedy approved these changes
Lgtm

2024-08-22 19:25 UTC, merged